### ISSUE TITLE
[torchbench] basic_gnn_gcn failed with spirv error on llvm-target branch

### ISSUE THREAD

**Issue by weishi-deng** [intel/intel-xpu-backend-for-triton#568] opened 2024-02-26 07:29 UTC
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wdeng/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wdeng/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

data type | model | error
-- | -- | --
fp16_inference | basic_gnn_gcn | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'
fp16_training | basic_gnn_gcn | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'
amp fp16 training | dlrm | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'
fp16_training | dlrm | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'
amp fp16 training | hf_Longformer | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'
fp16_training | hf_Longformer | Invalid SPIR-V module: input SPIR-V module uses unknown extension   'SPV_EXT_shader_atomic_float16_add'

</body>

</html>

env:
GPU: Max 1100
Driver version:  803.29
oneAPI: 2024.1

Triton:  890b7402b6a4cbada9cd94484237b0416686cec4 (Tue Feb 20)
PyTorch: 0f6d72ce16bd4b30402dcad97144d17cd7bc53ed (Based on PyTorch 2.1)
IPEX: f496a32aed6d9ad4c70fcbbf2d3321a385affccb

HUGGINGFACE_PIN_COMMIT: 4.27.4

reproducer:
inductor_xpu_test.sh torchbench float16 training performance xpu 0 static 1 0 dlrm

**Comment by tdeng5** [comment] 2024-03-05 02:09
@etiotto , there is a workaround in spirv-path, which functionality works, need we port this workaround to LLVM-target?

**Comment by etiotto** [comment] 2024-03-26 14:54
@ienkovich another duplicate of the atomix fp16 issues.

**Comment by vlad-penkin** [comment] 2024-03-26 15:46
Duplicates
- #728

**Closed by vlad-penkin** 2024-03-26 15:46 UTC
Labels: bug, tests: e2e
