### ISSUE TITLE
[FA2 performance] make sure end2end perf of FA2 match POC branch

### ISSUE THREAD

**Issue by Dewei-Wang-sh** [intel/intel-xpu-backend-for-triton#1758] opened 2024-08-01 03:00 UTC

**Comment by quintinwang5** [comment] 2024-08-15 06:49
Using `attn_ttg` branch from Dewei's repo, there are still some failures about `"dyn_cast on a non-existent value"' failed.` on multiple Attributes. This may be caused by the absence of layout propagation or annotation in our previous passes. WIP to fixing it.

**Comment by Dewei-Wang-sh** [comment] 2024-08-19 06:43
https://github.com/intel/intel-xpu-backend-for-triton/pull/1866 merged

**Comment by quintinwang5** [comment] 2024-08-19 08:48
> #1866 merged

Still fail with the newest llvm-target branch, WIP to investigate.
```
decltype(auto) llvm::dyn_cast(const From&) [with To = mlir::triton::gpu::SharedEncodingAttr; From = mlir::Attribute]: Assertion `detail::isPresent(Val) && "dyn_cast on a non-existent value"' failed.
```

**Comment by quintinwang5** [comment] 2024-08-22 02:58
It works now. But there is a performance gap.
```
Z, H, N_CTX, D_HEAD, avg_tflops, max_tflops, min_tflops
4, 48, 1024, 64, 78.061, 81.4263, 73.4266
```

**Comment by quintinwang5** [comment] 2024-08-26 13:11
Two main differences found (`PoC` vs. `llvm-target`):
1. `declare spir_func <16 x i32> @llvm.genx.GenISA.LSC2DBlockReadAddrPayload.v16i32.p0i8` vs. `declare spir_func <32 x i32> @llvm.genx.GenISA.LSC2DBlockReadAddrPayload.v32i32.p0i8`
2.  `tail prefetch` in k-loop vs. no such `prefetch`

**Comment by Dewei-Wang-sh** [comment] 2024-09-09 02:31
need to close when we have almost the same perf.

**Comment by etiotto** [comment] 2024-09-11 18:26
> #2133 leads to big performance drop.

The performance drop has been fixed. The GEMM performance went back to were it was before that PR was merged.

**Comment by quintinwang5** [comment] 2024-09-12 08:37
FA performace of `llvm-target` branch can match the PoC branch now. See details in https://github.com/intel/intel-xpu-backend-for-triton/pull/2216. But there are still gaps with reported data. Possible reasons:

1. different driver config
2. different performance collecting/computing methods
3. other potential factors

WIP to investigate.

**Comment by etiotto** [comment] 2024-09-12 20:29
#2216 is merged so now the llvm-target branch should have the same performance as the POC branch.

**Comment by etiotto** [comment] 2024-09-12 20:31
@quintinwang5 I'll let it to you to lose this work item. I think this one can be closed, however, as you already noted, the FA performance reported on the POC branch back in June was better than it is currently so you might want to open a new PR to investigate further.

**Comment by quintinwang5** [comment] 2024-09-20 08:42
With https://github.com/intel/intel-xpu-backend-for-triton/pull/2299, we can get better performance.
![Image](https://github.com/user-attachments/assets/649e04c2-d5c8-4f89-aaf6-5e50fe3c231b)

**Comment by quintinwang5** [comment] 2024-09-25 02:20
The performance gap has been identified. It's mainly caused by:

1. intel.passes.ttgpuir.add_prefetch_block 
2. intel.passes.ttgpuir.add_pipeline

For **add_prefetch_block**, it does not consume `num_stages` in `compiler.py` of [PoC branch](https://github.com/Dewei-Wang-sh/intel-xpu-backend-for-triton/blob/a215613ec6a0f0a7914e62941a1d6bbed194cd5e/third_party/intel/backend/compiler.py#L95). But it's not the case in [main branch](https://github.com/intel/intel-xpu-backend-for-triton/blob/71d3acadbe28d8580a27d668bce0d88602278154/third_party/intel/backend/compiler.py#L103). We always set `num_stages` to 4 for all benchmark cases from [here](https://github.com/intel/intel-xpu-backend-for-triton/blob/71d3acadbe28d8580a27d668bce0d88602278154/benchmarks/triton_kernels_benchmark/flash_attention_fwd_benchmark.py#L162). So `num_stages` in PoC branch is always 3, but 4 in main branch. This is the main difference. This is why https://github.com/intel/intel-xpu-backend-for-triton/pull/2299 is helpful. It just tune `num_stages` from 4 to 3.
The other problem is seems we do not add `add_pipeline` to `compiler.py`. But we have it in [main branch](https://github.com/intel/intel-xpu-backend-for-triton/blob/71d3acadbe28d8580a27d668bce0d88602278154/third_party/intel/backend/compiler.py#L215).
The result of different pairs: (`num_stages` in `add_prefetch_block ` and `add_pipeline`, please note we compare `MAX` performance with PoC branch):
All 3:
```
attn-performance:
      Z     H    N_CTX  D_HEAD  Triton-GB/s  XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0   1.0  32.0  16384.0    64.0    12.517414   15.379383        12.517414       15.379383        12.517414       15.379383     102.542653    125.987906         102.542653        125.987906         102.542653        125.987906        NaN       NaN
1   2.0  32.0   8192.0    64.0    24.275753   30.785579        24.275753       30.785579        24.275753       30.785579      99.433484    126.097730          99.433484        126.097730          99.433484        126.097730        NaN       NaN
2   4.0  32.0   4096.0    64.0    54.404357   60.091395        54.404357       57.986442        54.404357       62.354928     111.420123    123.067178         111.420123        118.756234         111.420123        127.702892        NaN  0.051337
3   4.0  48.0   1024.0    64.0   216.238394  225.233181       194.240701      199.285912       227.703805      228.863447     110.714058    115.319389          99.451239        102.034387         116.584348        117.178085   0.050803  0.013238
4   8.0  32.0   2048.0    64.0   106.064080  116.776062       105.816557      113.998892       115.768817      125.898367     108.609618    119.578688         108.356154        116.734865         118.547269        128.919928        NaN       NaN
5  16.0  32.0   1024.0    64.0   209.283556  213.700706       208.438513      184.001059       216.984164      238.923608     107.153181    109.414761         106.720518         94.208542         111.095892        122.328887   0.000461  0.087510
6  32.0  32.0    512.0    64.0   315.469916  412.835336       296.522004      368.649018       321.156491      422.812899      80.760299    105.685846          75.909633         94.374149          82.216062        108.240102   0.012365  0.027653

```
prefetch 3 and pipeline 4:
```
attn-performance:
      Z     H    N_CTX  D_HEAD  Triton-GB/s  XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0   1.0  32.0  16384.0    64.0    12.995822   15.156528        12.995822       15.156528        12.995822       15.156528     106.461774    124.162279         106.461774        124.162279         106.461774        124.162279        NaN       NaN
1   2.0  32.0   8192.0    64.0    25.767496   30.276678        25.767496       30.276678        25.767496       30.276678     105.543663    124.013272         105.543663        124.013272         105.543663        124.013272        NaN       NaN
2   4.0  32.0   4096.0    64.0    52.609647   56.657775        52.609647       55.901693        52.609647       57.434584     107.744558    116.035123         107.744558        114.486668         107.744558        117.626027        NaN  0.019127
3   4.0  48.0   1024.0    64.0   220.707664  222.993942       201.391041      190.650183       226.800867      230.034946     113.002324    114.172898         103.112213         97.612894         116.122044        117.777892   0.021409  0.027567
4   8.0  32.0   2048.0    64.0   100.150524  109.612018        94.423781      100.126620       105.563564      124.552457     102.554137    112.242707          96.689951        102.529658         108.097089        127.541716        NaN       NaN
5  16.0  32.0   1024.0    64.0   203.181628  207.029003       184.021239      188.359897       209.244408      225.530523     104.028994    105.998850          94.218874         96.440267         107.133137        115.471628   0.033611  0.033247
6  32.0  32.0    512.0    64.0   291.502480  376.179194       282.349661      332.353720       295.477566      413.333734      74.624635     96.301874          72.281513         85.082552          75.642257        105.813436   0.011144  0.058456
```
prefetch 4 and pipeline 3:
```
ttn-performance:
      Z     H    N_CTX  D_HEAD  Triton-GB/s  XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0   1.0  32.0  16384.0    64.0    12.546246   15.105354        12.546246       15.105354        12.546246       15.105354     102.778846    123.743059         102.778846        123.743059         102.778846        123.743059        NaN       NaN
1   2.0  32.0   8192.0    64.0    25.094930   28.197000        25.094930       28.197000        25.094930       28.197000     102.788834    115.494913         102.788834        115.494913         102.788834        115.494913        NaN       NaN
2   4.0  32.0   4096.0    64.0    52.409145   56.253132        52.409145       55.213642        52.409145       57.332519     107.333930    115.206414         107.333930        113.077538         107.333930        117.416999        NaN  0.026625
3   4.0  48.0   1024.0    64.0   204.339925  215.508286       197.969032      173.318348       210.839678      226.474297     104.622041    110.340242         101.360145         88.738994         107.949915        115.954840   0.014959  0.061738
4   8.0  32.0   2048.0    64.0    90.521290  107.004383        87.467891       99.074147       104.446341      114.739544      92.693800    109.572488          89.567121        101.451926         106.953053        117.493293        NaN       NaN
5  16.0  32.0   1024.0    64.0   195.686911  205.020239       177.442781      184.852534       196.985040      236.432018     100.191699    104.970362          90.850704         94.644497         100.856340        121.053193   0.003279  0.076187
6  32.0  32.0    512.0    64.0   280.860734  371.604885       277.722495      340.032763       291.220545      389.172240      71.900348     95.130851          71.096959         87.048387          74.552459         99.628094   0.006035  0.038339
```
All 4(current case in main branch):
```
attn-performance:
      Z     H    N_CTX  D_HEAD  Triton-GB/s  XeTLA-GB/s  Triton-GB/s-min  XeTLA-GB/s-min  Triton-GB/s-max  XeTLA-GB/s-max  Triton-TFlops  XeTLA-TFlops  Triton-TFlops-min  XeTLA-TFlops-min  Triton-TFlops-max  XeTLA-TFlops-max  Triton-CV  XeTLA-CV
0   1.0  32.0  16384.0    64.0    12.515734   15.048045        12.515734       15.048045        12.515734       15.048045     102.528893    123.273585         102.528893        123.273585         102.528893        123.273585        NaN       NaN
1   2.0  32.0   8192.0    64.0    24.984684   29.089741        24.984684       29.089741        24.984684       29.089741     102.337266    119.151577         102.337266        119.151577         102.337266        119.151577        NaN       NaN
2   4.0  32.0   4096.0    64.0    48.570482   56.323010        48.570482       55.401437        48.570482       57.275757      99.472347    115.349525          99.472347        113.462142          99.472347        117.300750        NaN  0.023525
3   4.0  48.0   1024.0    64.0   192.836625  222.791332       170.085312      207.638820       202.102672      227.210394      98.732352    114.069162          87.083680        106.311076         103.476568        116.331722   0.042374  0.025079
4   8.0  32.0   2048.0    64.0    96.737683  109.262235        91.254912       92.177443        97.462622      120.595287      99.059388    111.884528          93.445030         94.389702          99.801725        123.489574        NaN       NaN
5  16.0  32.0   1024.0    64.0   192.802767  201.445853       185.527106      176.398025       195.220099      232.210598      98.715017    103.140277          94.989878         90.315789          99.952691        118.891826   0.007049  0.102187
6  32.0  32.0    512.0    64.0   280.344505  365.476865       276.122718      335.745761       285.910285      400.602098      71.768193     93.562077          70.687416         85.950915          73.193033        102.554137   0.003918  0.048856
```

**Comment by whitneywhtsang** [comment] 2024-09-25 19:20
![Screenshot 2024-09-25 151419](https://github.com/user-attachments/assets/78034c83-3786-4873-94f5-a4418984a027)
@quintinwang5 CI reported 2 shapes with >5% degradation from the reported numbers, is it consistent with your measurements?

**Comment by quintinwang5** [comment] 2024-09-26 00:19
> ![Screenshot 2024-09-25 151419](https://private-user-images.githubusercontent.com/54643204/370867445-78034c83-3786-4873-94f5-a4418984a027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTAyNDAsIm5iZiI6MTcyNzMwOTk0MCwicGF0aCI6Ii81NDY0MzIwNC8zNzA4Njc0NDUtNzgwMzRjODMtMzc4Ni00ODczLTk0ZjUtYTQ0MTg5ODRhMDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAwMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmY2NkNjI5MDE1YTliMTE3OTAxNjdjNGE0MWMyMGE2MjM0ZjAwNjU2ZDlkMGE2MWM5ZTYxMTA1ZDMzOTBhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WpjgG0cS6993fUhCRNDFANA0F_AigiVfiIG9h3_dztI) @quintinwang5 CI reported 2 shapes with >5% degradation from the reported numbers, is it consistent with your measurements?

Seems not.

**Comment by whitneywhtsang** [comment] 2024-09-26 00:50
> > ![Screenshot 2024-09-25 151419](https://private-user-images.githubusercontent.com/54643204/370867445-78034c83-3786-4873-94f5-a4418984a027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTAyNDAsIm5iZiI6MTcyNzMwOTk0MCwicGF0aCI6Ii81NDY0MzIwNC8zNzA4Njc0NDUtNzgwMzRjODMtMzc4Ni00ODczLTk0ZjUtYTQ0MTg5ODRhMDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAwMTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmY2NkNjI5MDE1YTliMTE3OTAxNjdjNGE0MWMyMGE2MjM0ZjAwNjU2ZDlkMGE2MWM5ZTYxMTA1ZDMzOTBhN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WpjgG0cS6993fUhCRNDFANA0F_AigiVfiIG9h3_dztI) @quintinwang5 CI reported 2 shapes with >5% degradation from the reported numbers, is it consistent with your measurements?
> 
> Seems not.

Can you please confirm if it is due to using average vs maximum TFlops? If not, can you please investigate the reason?

**Comment by quintinwang5** [comment] 2024-09-26 01:55
Newest [CI result](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11042507163/job/30674998532) until now vs. PoC data( max performance).
![image](https://github.com/user-attachments/assets/cb805836-1136-47a1-abe3-df9df6e2a5a5)

**Comment by quintinwang5** [comment] 2024-09-27 07:46
> Newest [CI result](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11042507163/job/30674998532) until now vs. reported PoC data( max performance). ![image](https://private-user-images.githubusercontent.com/68101902/370956112-cb805836-1136-47a1-abe3-df9df6e2a5a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDQwNzgsIm5iZiI6MTcyNzQwMzc3OCwicGF0aCI6Ii82ODEwMTkwMi8zNzA5NTYxMTItY2I4MDU4MzYtMTEzNi00N2ExLWFiZTMtZGY5ZGY2ZTJhNWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTg5ZDEyZjNlYzgzY2Q0NTMyNmU4OTJhMWY0Mjc4NjFkZjZjZjI3ODIyNGJiODk4NTQ3ZjIwZTkxOThkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DRpV6P6pG4vu87j8Utd472ad4D77-LkDS0UVB4oJvc0) For `2 32 8192 64`, it may have fluctuation. Because another local result is **104.457533**, which is **97.315%** of PoC. So I think we've aligned the MAX performance between main and PoC branches. Due to historical reason, we did not use average performance as the criteria of FlashAttention. But optimizing the average performance to match the reported data(max performance) should be another issue.

From the data in the same CI, I collect the average performance data of PoC branch. The result is:
![image](https://github.com/user-attachments/assets/6560ef51-1911-4fdb-80b4-efa2ae2e3ba8)
@whitneywhtsang @etiotto

**Closed** 2024-09-27 14:39 UTC
Labels: research, performance

**Comment by etiotto** [comment] 2024-09-27 15:11
Great job team!
