### ISSUE TITLE
[Performance] Torchbench models: hf_T5, densenet121's performance dropped >35% compared to v2.1

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#707] opened 2024-03-19 03:04 UTC
bash inductor_xpu_test.sh torchbench float16 training performance xpu 0 static 1 0 hf_T5

<img width="1180" alt="image" src="https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/1ef09020-551c-439d-933c-3e8c20fad937">

bash inductor_xpu_test.sh torchbench amp_fp16 inference performance xpu 0 static 1 0 densenet121

<img width="1178" alt="image" src="https://github.com/intel/intel-xpu-backend-for-triton/assets/76785525/fe9041ca-273f-4ea2-8f1a-846ccd808da6">

**Comment by quintinwang5** [comment] 2024-03-22 01:30
For densetnet121, it should be `amp_fp16 inference`

**Comment by quintinwang5** [comment] 2024-03-25 05:18
For this two models, very `zeCommandListAppendBarrier` calls are observed. This is caused by the [default LOG_LEVEL](https://github.com/intel/intel-extension-for-pytorch/blob/faadb009c12ed4fb3133db9a10020726016b3d24/csrc/gpu/utils/Settings.cpp#L132) of IPEX which is used for Triton 3.0 E2E test. `WARN` LOG_LEVEL will enable `queue_barrier` (which will call `zeCommandListAppendBarrier` in level_zero), and [this ](https://github.com/intel/intel-extension-for-pytorch/blob/faadb009c12ed4fb3133db9a10020726016b3d24/csrc/gpu/utils/DPCPP.h#L96)will  used for onednn kernel submissions. Just align the default `LOG_LEVEL `to `DISABLED `can resolve this problem.
![barrier](https://github.com/intel/intel-xpu-backend-for-triton/assets/68101902/75b6265e-127b-4173-844c-6d79ef6cab2e)

**Comment by quintinwang5** [comment] 2024-03-25 05:48
Close this issue due to no fix is needed. Just update our IPEX commit to f58b30e98b8ec419555a18963100a4b7f3708291.

**Closed by quintinwang5** 2024-03-25 05:48 UTC
Labels: tests: e2e, performance
