### ISSUE TITLE
[OCL interface] Matrix 2D load intel_sub_group_2d_block_read_32b_8r8x2c is lowered to GenISA in-correctly.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#1426] opened 2024-06-21 05:28 UTC
The full signature of the OCL `intel_sub_group_2d_block_read_32b_8r8x2c(void AS1*, int, int, int, int __vector(2), unsigned int*)`.

In sub-group-size=16 case, the expected to be lowered to:
`llvm.genx.GenISA.LSC2DBlockRead.v8i32`
But it is lowered to:
`llvm.genx.GenISA.LSC2DBlockRead.v16i32(i64, i32, i32, i32, i32, i32, i32, i32, i32, i32, i1, i1, i32)`.

On Triton side, to use the GenISA instead of OCL. Need to track this on IGC side for fix.

**Comment by whitneywhtsang** [comment] 2024-06-21 13:16
The problem is already reported and fixed in next agama driver.

**Closed** 2024-06-21 22:30 UTC
