### ISSUE TITLE
[hf][performance] BF16 support for atomic support

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#285] opened 2024-01-17 07:32 UTC
When running `amp_bf16` training on the following HuggingFace models, it will fail due to the `atomic_add does not support bf16` error.

- AllenaiLongformerBase
- GPT2ForSequenceClassification
- XLNetLMHeadModel

Note that we also encountered the same behavior on CUDA, thus this could be marked as low priority for now.

**Comment by etiotto** [comment] 2024-02-12 16:25
Moving to next iteration, given that this also fails also for NVIDIA.

**Comment by whitneywhtsang** [comment] 2024-02-17 22:24
Cannot reproduce the failures. 
```
Stonepia/pytorch	dev/triton-test-3.0	0f6d72ce16bd4b30402dcad97144d17cd7bc53ed
intel/intel-xpu-backend-for-triton	c5e75f5563e52fc1b1e810b33d152d3b0f448f33	
intel-extension-for-pytorch 2.1.10+git99b4297
torch                       2.1.0a0+git0f6d72c
transformers                4.27.4
```

**Comment by etiotto** [comment] 2024-02-20 14:13
@Stonepia given this comment https://github.com/intel/intel-xpu-backend-for-triton/issues/285#issuecomment-1950448152 is it OK to close this one ?

**Comment by Stonepia** [comment] 2024-02-22 06:14
Hi @etiotto @whitneywhtsang , that should be triggered on this line:
https://github.com/intel/intel-xpu-backend-for-triton/blob/890b7402b6a4cbada9cd94484237b0416686cec4/python/triton/language/semantic.py#L1102

Could you check if you are reproducing using the `training mode`? My run command is:

```bash
bash inductor_xpu_test.sh huggingface amp_bf16 training performance xpu 0 static 1 0 AllenaiLongformerBase
```


```Python
  File "/home/machine/user/intel-xpu-backend-for-triton/python/triton/language/core.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/home/machine/user/intel-xpu-backend-for-triton/python/triton/language/core.py", line 1265, in atomic_add
    return semantic.atomic_add(pointer, val, mask, sem, scope, _builder)
  File "/home/machine/user/intel-xpu-backend-for-triton/python/triton/language/semantic.py", line 1176, in atomic_add
    ptr, val, mask = atom_red_typechecking_impl(ptr, val, mask, 'add', builder)
  File "/home/machine/user/intel-xpu-backend-for-triton/python/triton/language/semantic.py", line 1086, in atom_red_typechecking_impl
    raise ValueError("atomic_" + op + " does not support " + str(element_ty))
ValueError: atomic_add does not support bf16

triton.compiler.errors.CompilationError: at 11:70:def triton_poi_fused_index_add_new_zeros_14(in_ptr0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 9437184
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + ((16384*((x0 // 49152) % 4)) + (98304*(x0 // 196608)) + (x0 % 49152)), None)
    tmp2 = tl.load(in_ptr1 + (x0), None).to(tl.float32)
    tmp1 = tl.where(tmp0 < 0, tmp0 + 4718592, tmp0)
    # tl.device_assert((0 <= tmp1) & (tmp1 < 4718592), "index out of bounds: 0 <= tmp1 < 4718592")
    tl.atomic_add(out_ptr0 + (tl.broadcast_to(tmp1, [XBLOCK])), tmp2, None)
                                                                      ^
ValueError('atomic_add does not support bf16')
```

**Comment by whitneywhtsang** [comment] 2024-02-23 03:41
@Stonepia The atomic failure for all 3 benchmarks can be reproduced with performance scenario, but not with accuracy scenario.

**Comment by whitneywhtsang** [comment] 2024-02-23 03:48
Should be the same issue as https://github.com/intel/intel-xpu-backend-for-triton/issues/152.

**Comment by etiotto** [comment] 2024-03-26 14:52
@ienkovich duplicate of the other issue on atomic support for fp16 you are working on.

**Comment by vlad-penkin** [comment] 2024-03-26 15:52
Duplicates
- #728

**Closed by vlad-penkin** 2024-03-26 15:52 UTC
Labels: bug, tests: e2e

**Comment by ienkovich** [comment] 2024-03-27 19:39
This issue and all duplicates except #285 should be fixed with `TRITON_INTEL_EMULATE_FP16_ATOMICS=1` env set.

#285 is about atomics support for `bfloat16`. This is not supported for all backends. I think we shouldn't add emulation for something that is not supported on any backend.
