### ISSUE TITLE
[Productize Flash Attention performance] Features

### ISSUE THREAD

**Issue by vlad-penkin** [intel/intel-xpu-backend-for-triton#1451] opened 2024-06-22 11:58 UTC
This is the Flash Attention Performance features productization umbrella ticket. Before converting this ticket umbrella ticket, please:
- Add the step-by-step Flash Attention Performance features productization plan here.
- Create a separate ticket for each step and list it here. For ease of tracking,  prefix the ticket title with [Productize Flash Attention #step_number]
- Add the definition of done for this ticket. The definition of done may state that all commits from PoC have been merged and CI run on the main branch shows no difference on performance numbers comparing to the PoC branch

cc: @chengjunlu, @quintinwang5, @Dewei-Wang-sh, @etiotto, @whitneywhtsang, @tdeng5, @LiyangLingIntel

**Comment by vlad-penkin** [comment] 2024-06-22 12:01
This ticket is related to:
- #1450

**Comment by chengjunlu** [comment] 2024-06-24 01:02
Update the status for the flash attention performance on the fallback path from the issue https://github.com/intel/intel-xpu-backend-for-triton/issues/878.

The flash attention optimization notes.
The most passes are aligned with the GEMM optimization.
Here is some memo specific for the flash attention optimization:

Already finished:
- Reduce the number of the convert layout between the chained dot operations.
-- Remove redundant convert layout: #894 
- We can remove the un-necessary convert layout for the Q matrix. The dot layout can be backward combine all the way back to the  ops when load the Q operands. As show in the pieces of the MLIR. https://github.com/intel/intel-xpu-backend-for-triton/issues/950

Things need to be finished:
- We need to optimize the convert layout op lowering by not using SLM and extra synchronization for PVC, Dtype fp16/bf16. Because it is coincidence we can feed the output from the first DPAS inst directly as the operands A to the second DPAS. The tt.dot if fully paralleled on the row dimension.  https://github.com/intel/intel-xpu-backend-for-triton/issues/951

**Comment by Dewei-Wang-sh** [comment] 2024-06-24 02:27
@vlad-penkin is this issue meant to our flash attention Poc for the demo show with Habana(the block pointer path we are working) or not?

**Comment by Dewei-Wang-sh** [comment] 2024-06-24 03:56
features need to be productize
- #1457 
- #1458  
- #1459 
- #1461 
- #1462
- #1303 
- #1201

**Comment by Dewei-Wang-sh** [comment] 2024-08-19 06:44
code are all merged, still need https://github.com/intel/intel-xpu-backend-for-triton/issues/1758 to make sure the llvm-target branch can reproduce the perf of poc branch.

**Closed** 2024-09-13 18:11 UTC
Labels: enhancement, performance, codegen: attention, umbrella
