### ISSUE TITLE
[language/test_line_info.py::dot_combine] Insert #dpas for dot operator

### ISSUE THREAD

**Issue by prathams417** [intel/intel-xpu-backend-for-triton#263] opened 2024-01-15 21:12 UTC
Figure out how to insert #dpas to enable dot_operator test by using #mma as reference.

Ex:
` %10 = triton_gpu.convert_layout %9 : (tensor<32x32xi8, #shared1>) -> tensor<32x32xi8, #triton_gpu.dot_op<{opIdx = 0, parent = #mma, kWidth = 4}>> loc(#loc5) `
` %11 = triton_gpu.convert_layout %8 : (tensor<32x32xi8, #shared>) -> tensor<32x32xi8, #triton_gpu.dot_op<{opIdx = 1, parent = #mma, kWidth = 4}>> loc(#loc5) `
` %12 = tt.dot %10, %11, %cst {allowTF32 = true, maxNumImpreciseAcc = 0 : i32} : tensor<32x32xi8, #triton_gpu.dot_op<{opIdx = 0, parent = #mma, kWidth = 4}>> * tensor<32x32xi8, #triton_gpu.dot_op<{opIdx = 1, parent = #mma, kWidth = 4}>> -> tensor<32x32xi32, #mma> loc(#loc6) `

**Comment by prathams417** [comment] 2024-01-16 20:41
Currently, Nvidia generates #mma's in the AccelerateMatmul.cpp file, specifically in BlockedToMMA(). Need to create something similar for GenX to insert #dpas. @pengtu is working to complete this.

**Comment by ienkovich** [comment] 2024-01-30 21:35
@prathams417 @vlad-penkin
To me, this task looks like an integral part of DPAS enabling for `tt.dot` which has to be aligned with the lowering part. I don't know what I am here assigned for. Why do we need this issue in addition to #145?

**Comment by whitneywhtsang** [comment] 2024-01-31 22:00
Duplicate of https://github.com/intel/intel-xpu-backend-for-triton/issues/145.

**Closed by whitneywhtsang** 2024-01-31 22:00 UTC
Labels: enhancement
