### ISSUE TITLE
Core tests regression with the latest rolling stable driver release (821)

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#786] opened 2024-04-02 02:38 UTC
```
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-rows-False-float16-float32] - AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.001
Mismatched elements: 109 / 4096 (2.66%)
Max absolute difference: 0.1367
Max relative difference: 0.112
x: array([[0.9087, 1.035 , 0.8047, ..., 1.025 , 0.6855, 1.1   ],
       [0.8516, 1.134 , 0.868 , ..., 1.048 , 0.838 , 1.057 ],
       [1.125 , 1.065 , 1.172 , ..., 1.177 , 1.087 , 1.19  ],...
y: array([[0.9087, 1.035 , 0.8047, ..., 1.025 , 0.6855, 1.101 ],
       [0.8516, 1.134 , 0.8677, ..., 1.048 , 0.838 , 1.057 ],
       [1.125 , 1.065 , 1.172 , ..., 1.177 , 1.087 , 1.19  ],...
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-add-cols-False-float16-float32] - AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.001
Mismatched elements: 109 / 4096 (2.66%)
Max absolute difference: 0.1367
Max relative difference: 0.12
x: array([[0.9087, 1.279 , 1.02  , ..., 1.072 , 0.853 , 1.265 ],
       [0.8047, 1.331 , 1.036 , ..., 1.048 , 0.9585, 1.174 ],
       [0.9136, 1.098 , 1.176 , ..., 1.012 , 1.043 , 1.144 ],...
y: array([[0.9087, 1.279 , 1.0205, ..., 1.072 , 0.853 , 1.265 ],
       [0.8047, 1.331 , 1.036 , ..., 1.048 , 0.9585, 1.174 ],
       [0.9136, 1.098 , 1.176 , ..., 1.012 , 1.043 , 1.144 ],...
FAILED language/test_core.py::test_dot[1-64-64-64-4-False-False-none-False-float16-float32] - AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.001
Mismatched elements: 124 / 4096 (3.03%)
Max absolute difference: 0.1373
Max relative difference: 122.75
x: array([[-0.02618 ,  0.1003  , -0.1304  , ...,  0.09045 , -0.2494  ,
         0.165   ],
       [-0.1304  ,  0.1521  , -0.114   , ...,  0.06573 , -0.144   ,...
y: array([[-0.02618 ,  0.1003  , -0.1304  , ...,  0.09045 , -0.2494  ,
         0.165   ],
       [-0.1304  ,  0.1521  , -0.114   , ...,  0.06573 , -0.144   ,...
= 3 failed, 8868 passed, 317 skipped, 835 xfailed, 181 warnings in 471.08s (0:07:51) =
```

Tested with both oneAPI 2024.0.1 and 2024.1.0, same tests failing.
Example: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8514498212/job/23324433861

**Comment by whitneywhtsang** [comment] 2024-04-08 02:47
duplicate of https://github.com/intel/intel-xpu-backend-for-triton/issues/797?

**Comment by pbchekin** [comment] 2024-04-08 19:28
> duplicate of #797?

Yes, closing as duplicate.

**Closed** 2024-04-08 19:29 UTC
Labels: bug, tests: ut, dependencies
