### ISSUE TITLE
[PyTorch Upstream] unknown extension 'SPV_EXT_shader_atomic_float16_add'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#728] opened 2024-03-22 08:03 UTC
We found a triton comile error in pytorch Inductor UT:  `Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_EXT_shader_atomic_float16_add'`.

To reproduce this error:
Triton commit：（latst llvm-target) 4bb063ee2f6280d3d9719a3b41952fcb16a5fefe

Run case in IPEX:
python tests/gpu/pytorch/test/inductor/test_torchinductor.py  -k test_scatter_add2_xpu

Error message:
InvalidModule: Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_EXT_shader_atomic_float16_add'

**Comment by etaf** [comment] 2024-03-22 08:26
@vlad-penkin @riverliuintel This issue fails a series of upstream pytroch Inductor test cases, please prioritize.

**Comment by vlad-penkin** [comment] 2024-03-22 11:50
This issue is related to:
- #282

**Comment by etiotto** [comment] 2024-03-22 15:45
@ienkovich this is likely a duplicate of #282.

**Comment by etaf** [comment] 2024-03-26 02:46
@etiotto @vlad-penkin @riverliuintel :
I found this case has diffrenet beheavior between my two PVC machine, one(Max 1100) got `Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_EXT_shader_atomic_float16_add'`, But the other PVC( Max 1550
) machine got `nan` value.  Does this expected?

**Comment by etiotto** [comment] 2024-03-26 14:17
> Max 1550

This is surprising to me because AFAIK all PVC GPUs do not support atomic operations in HW for fp16.

**Comment by vlad-penkin** [comment] 2024-03-26 15:45
This issue is duplicated by:
- #286 
- #568

**Comment by vlad-penkin** [comment] 2024-03-28 15:06
@riverliuintel emulation is already implemented and merged into the llvm-target branch, see linked PR:
- #760

**Comment by riverliuintel** [comment] 2024-04-11 01:17
@vlad-penkin If not set this flag 'TRITON_INTEL_EMULATE_FP16_ATOMICS=1 ' obviously in test scripts, the functionality will be break. There is no place to set this flag in upstreamed PyTorch script repo for specific device. I suggest this flag can be set in Triton as default if the GPU hardware not support this feature. What's your opinion?

**Comment by riverliuintel** [comment] 2024-04-22 23:36
@vlad-penkin  please set this parameters as default for PVC.

**Closed** 2024-04-24 04:21 UTC
Labels: bug, upstream: pytorch
