### ISSUE TITLE
Unskipping test_flash_attention.py breaks regular runs

### ISSUE THREAD

**Issue by leshikus** [intel/intel-xpu-backend-for-triton#1109] opened 2024-05-13 15:10 UTC
The commit https://github.com/intel/intel-xpu-backend-for-triton/commit/e47fd9537aeb313cd048393ac50d71b25993ec56 enables several tests, this breaks conda basekit run.

See the log at
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9056251421/job/24878516034

**Comment by whitneywhtsang** [comment] 2024-05-13 15:14
Those `test_flash_attention` tests are enabled by 1e4fb6497c1e2c55b738a842d05f14ae995e07c9 and not e47fd9537aeb313cd048393ac50d71b25993ec56.
@leshikus Are you sure the failures are caused by e47fd9537aeb313cd048393ac50d71b25993ec56?

**Comment by leshikus** [comment] 2024-05-13 15:17
Whitney, probably you are correct. Both commits happen at the same day, I've just start noticing failures

**Comment by leshikus** [comment] 2024-05-13 15:30
@whitneywhtsang thank you for the help with the owner

**Comment by etiotto** [comment] 2024-05-14 14:29
@leshikus they pass without using the conda env. so can you explain what is the difference the conda env. introduces ?

**Comment by leshikus** [comment] 2024-06-10 13:38
@etiotto the conda env means the different environment, namely, different libraries and different library paths; in some cases when a compiler is called and the problems can happen due to different header resolution, but this particular problem looks more like a linking problem to me

**Comment by vlad-penkin** [comment] 2024-08-04 13:19
@leshikus can we close this ticket?

**Comment by whitneywhtsang** [comment] 2024-12-05 01:00
`test_flash_attention.py` no longer exists, closing this issue.

**Closed by whitneywhtsang** 2024-12-05 01:00 UTC
Labels: bug, ci, tests: tutorials
