### ISSUE TITLE
Segmentation fault in core test with Python 3.12

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1009] opened 2024-04-30 23:30 UTC
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8902749841/job/24449274628

```
Fatal Python error: Segmentation fault
...
Current thread 0x00007fdd4d367740 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/triton/backends/intel/compiler.py", line 190 in make_spv
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/triton/backends/intel/compiler.py", line 198 in <lambda>
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/triton/compiler/compiler.py", line 280 in compile
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/triton/runtime/jit.py", line 526 in run
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/triton/runtime/jit.py", line 209 in <lambda>
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/test/unit/language/test_core.py", line 392 in do_test
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/test/unit/language/test_core.py", line 396 in _test_binary
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/test/unit/language/test_core.py", line 474 in test_bin_op
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/python.py", line 162 in pytest_pyfunc_call
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/python.py", line 1627 in runtest
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 173 in pytest_runtest_call
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 241 in <lambda>
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 341 in from_call
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 240 in call_and_report
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 135 in runtestprotocol
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/runner.py", line 116 in pytest_runtest_protocol
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/xdist/remote.py", line 195 in run_one_test
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/xdist/remote.py", line 174 in pytest_runtestloop
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/main.py", line 339 in _main
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/main.py", line 2[85](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8902749841/job/24449274628#step:12:86) in wrap_session
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/xdist/remote.py", line 393 in <module>
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 1291 in executetask
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 341 in run
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 411 in _perform_spawn
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 3[89](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8902749841/job/24449274628#step:12:90) in integrate_as_primary_thread
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 1273 in serve
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/execnet/gateway_base.py", line 1806 in serve
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19[93](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8902749841/job/24449274628#step:12:94)7, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, cython.cimports.libc.math, Cython.Utils, Cython.Plex.Actions, Cython.Plex.Transitions, Cython.Plex.Machines, Cython.Plex.DFA, Cython.Plex.Scanners, Cython.Compiler.Scanning, Cython.StringIOTree, Cython.Compiler.Code, markupsafe._speedups, spirv_utils, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._cdflib, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.special.cython_special, scipy.stats._stats, scipy.stats.beta_ufunc, scipy.stats._boost.beta_ufunc, scipy.stats.binom_ufunc, scipy.stats._boost.binom_ufunc, scipy.stats.nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, scipy.stats.ncf_ufunc, scipy.stats._boost.ncf_ufunc, scipy.stats.ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, scipy.stats.nct_ufunc, scipy.stats._boost.nct_ufunc, scipy.stats.skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, scipy.stats.invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, arch_utils (total: 137)
Fatal Python error: Segmentation fault
```

**Comment by vlad-penkin** [comment] 2024-05-01 14:18
Two related Python 3.12 issues:
- #1004 
- #1008

**Comment by ienkovich** [comment] 2024-05-01 23:32
The problem is reproducible using any Triton test. Segfault occurs on an attempt to return generated SPIR-V code to Python using `pybind11:bytes`. The reason is unclear yet.

**Comment by ienkovich** [comment] 2024-05-02 00:41
The problem is in GIL which is released in `translate_to_spirv` and not acquired back before creating Python object.

**Closed** 2024-05-02 01:48 UTC
Labels: bug, tests: ut
