### ISSUE TITLE
Investigate failing benchmarks on subgroup size 16

### ISSUE THREAD

**Issue by victor-eds** [intel/intel-xpu-backend-for-triton#1369] opened 2024-06-17 15:45 UTC
Some benchmarks are failing when subgroup size is set to 16:

- `huggingface YituTechConvBert amp_bf16 training`
- `huggingface YituTechConvBert bf16 training`

Found in: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9499093865

Error is:

```
RuntimeError: Triton Error [ZE]: 0x78000011
```

Env:

```
TIMESTAMP=20240613123916
JOB_NAME=huggingface-inference-amp_bf16
GITHUB_RUN_ID=9499093865
GITHUB_RUN_NUMBER=102
GITHUB_RUN_ATTEMPT=1
PYTHON_VERSION=3.10
PYTORCH_REPO=Stonepia/pytorch
PYTORCH_COMMIT_ID=22ce6c6508d1d13b263d4c8b1fd6b98505983e92
IPEX_REPO=
IPEX_COMMIT_ID=
LLVM_REPO=llvm/llvm-project
LLVM_COMMIT_ID=765206e050453018e861637a08a4520f29238074
BENCHMARK_REPO=weishi-deng/benchmark.git
BENCHMARK_COMMIT_ID=e90564f719a8df7daf0cff4a245404c435b7693a
TRITON_REPO=intel/intel-xpu-backend-for-triton
TRITON_COMMIT_ID=b25bf436956b8fce31bdd8dba68a9aa3959917e6
TORCHVISION_COMMIT_ID=
TORCHTEXT_COMMIT_ID=
TORCHAUDIO_COMMIT_ID=
TRANSFORMERS_VERSION=4.27.4
TIMM_COMMIT_ID=b9d43c7dcac1fe05e851dd7be7187b108af593d2
LIBIGC1_VERSION=1.0.16510.19-881
LEVEL_ZERO_VERSION=1.3.29138.29-881
GPU_DEVICE=Intel(R) Data Center GPU Max 1550
AGAMA_VERSION=881
```

Create followup issues to fix this error.

**Comment by pengtu** [comment] 2024-06-17 21:04
The Level Zero error code complains that a kernel name is not found in the module:
    
ERROR_INVALID_KERNEL_NAME = 0x78000011          ## [Validation] kernel name is not found in the module

**Comment by sommerlukas** [comment] 2024-07-22 12:43
So far, we haven't been able to reproduce this behavior on the current `llvm-target` branch. Will investigate further.

**Comment by sommerlukas** [comment] 2024-07-29 12:21
Work on this ticket had been blocked by #1647 for most of last week. We were able to obtain data from a CI run end of last week and will present a summary offline in the meeting.

**Comment by sommerlukas** [comment] 2024-07-30 08:42
Comparison of https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10108590708 and https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10108584426 shows that there are no benchmarks that fail specifically for subgroup size 16. 

The following configurations failed in both CI runs:
```
Both failed (16 configurations):
     dev        suite                           name       mode  datatype  speedup 32  speedup 16
21   xpu  huggingface                     GoogleFnet  inference   float16         0.0         0.0
48   xpu  huggingface          AllenaiLongformerBase   training  bfloat16         0.0         0.0
66   xpu  huggingface  GPT2ForSequenceClassification   training  bfloat16         0.0         0.0
67   xpu  huggingface                     GoogleFnet   training  bfloat16         0.0         0.0
90   xpu  huggingface               XLNetLMHeadModel   training  bfloat16         0.0         0.0
113  xpu  huggingface                     GoogleFnet  inference   float32         0.0         0.0
159  xpu  huggingface                     GoogleFnet  inference  amp_bf16         0.0         0.0
205  xpu  huggingface                     GoogleFnet  inference  bfloat16         0.0         0.0
251  xpu  huggingface                     GoogleFnet  inference  amp_fp16         0.0         0.0
278  xpu  huggingface          AllenaiLongformerBase   training  amp_bf16         0.0         0.0
296  xpu  huggingface  GPT2ForSequenceClassification   training  amp_bf16         0.0         0.0
297  xpu  huggingface                     GoogleFnet   training  amp_bf16         0.0         0.0
320  xpu  huggingface               XLNetLMHeadModel   training  amp_bf16         0.0         0.0
343  xpu  huggingface                     GoogleFnet   training   float16         0.0         0.0
389  xpu  huggingface                     GoogleFnet   training   float32         0.0         0.0
435  xpu  huggingface                     GoogleFnet   training  amp_fp16         0.0         0.0
```

Will close this issue, as these failures occur for both subgroup sizes and are not specific to subgroup size 16.

For the following configurations, the problem is `atomic_add does not support bf16`:
```
48   xpu  huggingface          AllenaiLongformerBase   training  bfloat16         0.0         0.0
66   xpu  huggingface  GPT2ForSequenceClassification   training  bfloat16         0.0         0.0
90   xpu  huggingface               XLNetLMHeadModel   training  bfloat16         0.0         0.0
278  xpu  huggingface          AllenaiLongformerBase   training  amp_bf16         0.0         0.0
296  xpu  huggingface  GPT2ForSequenceClassification   training  amp_bf16         0.0         0.0
320  xpu  huggingface               XLNetLMHeadModel   training  amp_bf16         0.0         0.0
```

For the remaining configurations, which all use the same model, https://github.com/intel/intel-xpu-backend-for-triton/issues/1731 was filed.

**Closed by sommerlukas** 2024-07-30 08:42 UTC
Labels: bug, tests: e2e, upstream: pytorch, performance, codegen: mlir
