### ISSUE TITLE
Fix UT `test_core.py::test_poison_return` failure

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#2482] opened 2024-10-13 03:42 UTC
Upstream commit https://github.com/triton-lang/triton/commit/d39ee1f9c288c9a442cc4c65861e8220b9423da0 added a new unit test `test_core.py::test_poison_return`, it is merged in https://github.com/intel/intel-xpu-backend-for-triton/pull/2481.
The test case expects to find `poison` in llir: `assert "poison" in h.asm["llir"], h.asm["llir"]`, but `poison` is optimized away with LLVM opt.

To reproduce remove
```
    if is_xpu():
        pytest.skip("FIXME: poison is optimized away by opt")
```

**Comment by Retribution98** [comment] 2024-11-12 08:56
I've figured out the problem. I think it is not a problem for xpu, and we should not expect the second poison in this test case.

The main reason for this problem is that we use different commands to store data in LLVM IR. Cuda converts tt.store to `inline_asm` command, and we convert it to `llvm.store`.
Then the LLVM optimizer for the SROA function removes `llvm.store` with the `poison` value, but ignores the cuda assembly instruction.
I think this is expected behavior, since in this case we are not storing any values.

I suggest removing the omission of this test, but not using the last assert.
Could I push these changes to upstream?
@whitneywhtsang, what do you think about this?

**Comment by whitneywhtsang** [comment] 2024-11-12 10:34
Make sense, please make the suggestion of removing the last assertion upstream.

**Comment by Retribution98** [comment] 2024-11-12 13:22
The upstream [PR ](https://github.com/triton-lang/triton/pull/5124) is merged.
I also create the local PR to remove `pytest.skip` in this test.

**Closed** 2024-11-12 15:29 UTC
Labels: bug, tests: ut
