### ISSUE TITLE
[PT2.3][PVC][DDP]dlrmv2 dynamo inference meets RuntimeError: Native API failed. Native API returns: -5 (PI_ERROR_OUT_OF_RESOURCES) -5 (PI_ERROR_OUT_OF_RESOURCES)

### ISSUE THREAD

**Issue by xiaowangintel** [intel/intel-xpu-backend-for-triton#1346] opened 2024-06-13 06:50 UTC
Hi, team, we got a runtime error if we run dlrm-v2 with torch.compile for pytorch2.3 on distributed mode.

The details you can read pytorch jira(https://jira.devtools.intel.com/browse/PYTORCHDGQ-4515?filter=-1)

On the debug process, I have got a reproducer([4515_reproducer_test_3.py](https://jira.devtools.intel.com/secure/attachment/4393391/4393391_4515_reproducer_test_3.py)) with TORCH_COMPILE_DEUBG=1. You can got same error through this reproducer.

**Comment by vlad-penkin** [comment] 2024-06-21 02:14
Won't fix. No confirmation that this is Triton issue since it's reproducible only in the multi-card use case on the certain device number (3 from the range of 0 to 7). Triton XPU 3.0 works on a single tile and supports PyTorch 2.4, IPEX version in question is based on the PyTorch 2.3.

**Closed** 2024-06-21 02:14 UTC
Labels: bug, wontfix, tests: e2e, ipex
