### ISSUE TITLE
[operators/test_flash_attention.py::test_op] Fix failures with `TRITON_INTERPRET=1`

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#598] opened 2024-02-29 21:50 UTC
TRITON_INTERPRET=1 python3 -m pytest --junitxml=~/reports/flash_attention.xml -n 8 -m interpreter -vvv -s python/test/unit/operators/test_flash_attention.py::test_op --device cpu

**Comment by tdeng5** [comment] 2024-03-05 02:02
It's a debug feature, propose to lower the priority to P2.

**Comment by Sarbojit2019** [comment] 2024-03-07 07:19
I could see 8 tests are failing. I have fixed 4 tests but remaining 4 tests are failing because gemm for 'Half' data type is not implemented.
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/52556743/7f3057fa-1872-4274-a9d2-ba4fcdcffcc5)

torch.matmul call is throwing the error.
![image](https://github.com/intel/intel-xpu-backend-for-triton/assets/52556743/84d1ad8e-2160-4b84-820d-2093d2afae08)

@whitneywhtsang 
I did a quick search in source code here : https://github.com/Stonepia/pytorch. It seems baddbmm_with_gemm() is implemented in Pytorch. I don't know which component (Pytorch or IEPX) has to get Half implemented.

**Comment by whitneywhtsang** [comment] 2024-03-11 19:17
@vlad-penkin Please open an issue for PyTorch team for the `baddbmm_with_gemm not implemented for Half` failure.

**Comment by etiotto** [comment] 2024-04-12 14:59
> [@vlad-penkin](https://github.com/vlad-penkin) Please open an issue for PyTorch team for the `baddbmm_with_gemm not implemented for Half` failure.

@vlad-penkin  odo we have support for the above ?

**Comment by anmyachev** [comment] 2024-07-30 15:23
@etiotto @whitneywhtsang can we close this issue since this test has been moved to https://github.com/triton-lang/kernels? 

I also tried https://github.com/triton-lang/kernels/blob/main/test/test_flash_attention.py with upstream pytorch (without IPEX) and small changes: 
* removed `import triton.ops` due to (`ModuleNotFoundError: No module named 'triton.ops'`).
* added `return` after `p = torch.matmul(q, k.transpose(2, 3)) * sm_scale`.

`RuntimeError: "baddbmm_with_gemm" not implemented for 'Half'` the problem no longer reproduces.

**Comment by whitneywhtsang** [comment] 2024-07-30 15:52
I am OK to close this issue.

**Comment by anmyachev** [comment] 2024-08-01 21:11
> I am OK to close this issue.

I'll close it then

**Closed by anmyachev** 2024-08-01 21:11 UTC
Labels: bug, tests: ut
