### ISSUE TITLE
error with use of tensor.dtype.element_ty

### ISSUE THREAD

**Issue by rgiduthuri-intel** [intel/intel-xpu-backend-for-triton#629] opened 2024-03-06 02:40 UTC
The use of `tensor.dtype.element_ty` in the below Triton kernel is producing an error (pasted at the end of this message). I'm using the latest llvm-target build as of few hours ago. [The PT 2.1 with CUDA didn't report the error]. Appreciate any quick workaround suggestions. Thanks

```
import torch
import triton
import triton.language as tl

@triton.jit
def kernel(
      out, e_dst, e_src, adj1, adj2, num_rows,
      WG_SIZE : tl.constexpr
  ):
    zero_indices = tl.zeros((WG_SIZE,), dtype=adj2.dtype.element_ty)
    zero_values = tl.zeros((WG_SIZE,), dtype=e_src.dtype.element_ty)


if __name__ == '__main__':
    if torch.cuda.device_count() > 0:
        device = torch.device('cuda')
    else:
        import intel_extension_for_pytorch
        device = torch.device('xpu')

    num_rows, num_cols, num_indices, heads = 16, 16, 16, 4
    e_src = torch.randn((num_cols,heads), dtype=torch.float32, device=device) + 0.5
    e_dst = torch.randn((num_rows,heads), dtype=torch.float32, device=device) + 0.5
    adj1 = torch.zeros(num_rows + 1, dtype=torch.int32, device=device)
    adj2 = torch.randint(num_rows, (num_indices,), dtype=torch.int32, device=device)
    out = torch.empty((num_indices,heads), dtype=e_src.dtype, device=e_src.device)
    # invoke triton kernel
    launch_grid = (num_rows * heads // 256,)
    kernel[launch_grid](out, e_dst, e_src, adj1, adj2, num_rows, 256)
```

Here's the error message:
```
  File "/home/rgiduthu/miniconda3/lib/python3.11/ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/home/rgiduthu/triton-dev-llvm-target/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 47, in visit_Attribute
    return getattr(lhs, node.attr)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'torch.dtype' object has no attribute 'element_ty'
```

**Comment by Sarbojit2019** [comment] 2024-03-13 10:26
Hello @rgiduthuri-intel,

I have made minor modification in your kernel code and with that sample code runs successfully. While I am trying to root cause the issue I think this workaround will unblock you. 
========= Original code ===========
@triton.jit
def kernel(
      out, e_dst, e_src, adj1, adj2, num_rows,
      WG_SIZE : tl.constexpr
  ):
    zero_indices = tl.zeros((WG_SIZE,), dtype=adj2.dtype.element_ty)
    zero_values = tl.zeros((WG_SIZE,), dtype=e_src.dtype.element_ty)

============= Modified code ==========
@triton.jit
def kernel(
      out_, e_dst_, e_src_, adj1_, adj2_, num_rows_,
      WG_SIZE : tl.constexpr
  ):
    zero_indices = tl.zeros((WG_SIZE,), dtype=adj2_.dtype.element_ty)
    zero_values = tl.zeros((WG_SIZE,), dtype=e_src_.dtype.element_ty)

To me looks like it is name conflict issue as change in kernel parameter names (notice the additional '_' to each parameters) resolved the error.

**Comment by Sarbojit2019** [comment] 2024-03-14 08:43
@rgiduthuri-intel, 
I did further investigations and found even with latest Triton (branch:main) fails with on NVidia machine. Triton 2.2.1 passes the test. You might have installed using pip which installs Triton 2.2.1 hence you saw it is passing.

**Conclusion**: It is not a Intel Triton issue but it is Triton 3.0 issue. @chengjunlu has already raised the fix #629. Until fix gets merged and unstreamed please use the workaround I have suggested.

Thanks

**Comment by rgiduthuri-intel** [comment] 2024-03-15 18:59
Great! Thanks for the workaround. Please feel free to close this issue.

**Comment by whitneywhtsang** [comment] 2024-03-15 19:29
@Sarbojit2019 As discussed, please post a PR in OpenAI repo to fix this issue.

**Closed** 2024-05-06 14:21 UTC
Labels: bug, tests: ut
