### ISSUE TITLE
[test_blocksparse.py::test_attention_fwd_bwd] fails to run correctly on PVC

### ISSUE THREAD

**Issue by ESI-SYD** [intel/intel-xpu-backend-for-triton#251] opened 2024-01-15 01:57 UTC
Current error on test run:

```
E       AssertionError: Scalars are not close!
E       
E       Expected nan but got nan.
E       Absolute difference: nan (up to 0.001 allowed)
E       Relative difference: nan (up to 0 allowed)
```

To reproduce, comment out line 156 in file intel-xpu-backend-for-triton/python/test/unit/operators/test_blocksparse.py and run:

` python3 -m pytest --verbose --device xpu python/test/unit/operators/test_blocksparse.py::test_attention_fwd_bwd `

**Comment by tdeng5** [comment] 2024-01-19 07:05
This case can pass on SPIRV path but fail on LLVM path.

**Comment by ESI-SYD** [comment] 2024-01-29 07:43
`nan` in `torch_attn_out` and `triton_attn_out` raised assert error.

**Comment by ESI-SYD** [comment] 2024-01-29 15:20
https://github.com/intel/intel-xpu-backend-for-triton/issues/257

**Comment by etiotto** [comment] 2024-01-29 17:54
> `nan` in `attn_out` and `blocksparse.matmul`op incorrect calculation on XPU.#257

What do you mean ? Do you mean that #257 has the same issue as this one ?

**Comment by ESI-SYD** [comment] 2024-01-30 02:37
> > `nan` in `attn_out` and `blocksparse.matmul`op incorrect calculation on XPU.#257
> 
> What do you mean ? Do you mean that #257 has the same issue as this one ?

This issue depends on `matmul` fix in 257.

**Comment by prathams417** [comment] 2024-02-06 22:20
The issue is not resolved by disabling optimizations. Fails on both -O3 and -O0 optimizations levels so it is unlikely to be the same issue as #381

**Comment by vlad-penkin** [comment] 2024-02-09 15:41
When doing some tensor calculations on xpu, nan values are being generated instead of zeros. In the test_attention_fwd_bwd test which is in intel-xpu-backend-for-triton/python/test/unit/operators/test_blocksparse.py, the tensor that is generated as reference using torch produces a nan value. Using a reduced test case, we can see that the output generated on xpu is: 

Output tensor([[[[nan, -inf, -inf,  ..., -inf, -inf, -inf],
          [nan, nan, -inf,  ..., -inf, -inf, -inf],
          [nan, nan, nan,  ..., -inf, -inf, -inf],
          ...,
          [nan, nan, nan,  ..., nan, -inf, -inf],
          [nan, nan, nan,  ..., nan, nan, -inf],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='xpu:0',
       dtype=torch.float16)

whereas CUDA, which generates the correct result:

on cuda produces:

tensor([[[[0., -inf, -inf,  ..., -inf, -inf, -inf],

          [0., 0., -inf,  ..., -inf, -inf, -inf],

          [0., 0., 0.,  ..., -inf, -inf, -inf],

          ...,

          [0., 0., 0.,  ..., 0., -inf, -inf],

          [0., 0., 0.,  ..., 0., 0., -inf],

          [0., 0., 0.,  ..., 0., 0., 0.]]]], device='cuda:0',

       dtype=torch.float16)

**Comment by etiotto** [comment] 2024-02-12 17:57
@prathams417 are you still working on this?

**Comment by prathams417** [comment] 2024-02-12 17:58
> @prathams417 are you still working on this?

Yes, Although the torch portion of the test is behaving weirdly, I'm still investigating the triton kernel.

**Comment by prathams417** [comment] 2024-02-14 19:36
Triton result is now correct compared to CUDA after https://github.com/intel/llvm/pull/12709 was merged. num_programs(0) was the main cause of the issue as it was being lowered incorrectly

**Comment by vlad-penkin** [comment] 2024-02-20 13:50
@prathams417 can we close this issue?

**Comment by whitneywhtsang** [comment] 2024-03-04 16:07
Enabled by https://github.com/intel/intel-xpu-backend-for-triton/pull/614.

**Closed by whitneywhtsang** 2024-03-04 16:07 UTC
Labels: bug, tests: ut, dependencies
