### ISSUE TITLE
10 test cases in test_matmul.py failed when set the threads_per_warp to 16.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#435] opened 2024-02-02 06:08 UTC
Lowering the GEMM kernel to FMA ops with threads_per_warp to 16, 10 test cases in test_matmul.py failed.

This issue cannot be reproduced when set the LLVM optimization level to `O0` instead of `O3`. Need to further debug it with the LLVM optimization passes.

Here is the failed test cases.

```
2024-02-01T06:36:34.9848665Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-128-False-False-bfloat16-bfloat16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9848676Z 
2024-02-01T06:36:34.9848806Z Mismatched elements: 1625 / 24931 (6.5%)
2024-02-01T06:36:34.9849134Z Greatest absolute difference: 1.6015625 at index (56, 75) (up to 1e-05 allowed)
2024-02-01T06:36:34.9849390Z Greatest relative difference: 1.8203125 at index (8, 87) (up to 0.016 allowed)
2024-02-01T06:36:34.9850208Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-83-False-False-bfloat16-bfloat16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9850215Z 
2024-02-01T06:36:34.9850338Z Mismatched elements: 1645 / 24931 (6.6%)
2024-02-01T06:36:34.9850646Z Greatest absolute difference: 1.5 at index (16, 122) (up to 1e-05 allowed)
2024-02-01T06:36:34.9850894Z Greatest relative difference: 2.46875 at index (24, 84) (up to 0.016 allowed)
2024-02-01T06:36:34.9851673Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-128-False-True-float16-float16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9851687Z 
2024-02-01T06:36:34.9851804Z Mismatched elements: 1669 / 24931 (6.7%)
2024-02-01T06:36:34.9852125Z Greatest absolute difference: 1.6015625 at index (56, 75) (up to 1e-05 allowed)
2024-02-01T06:36:34.9852389Z Greatest relative difference: 1.8095703125 at index (8, 87) (up to 0.001 allowed)
2024-02-01T06:36:34.9853225Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-128-False-False-float16-float16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9853232Z 
2024-02-01T06:36:34.9853351Z Mismatched elements: 1908 / 24931 (7.7%)
2024-02-01T06:36:34.9853672Z Greatest absolute difference: 1.6015625 at index (56, 75) (up to 1e-05 allowed)
2024-02-01T06:36:34.9853931Z Greatest relative difference: 1.8095703125 at index (8, 87) (up to 0.001 allowed)
2024-02-01T06:36:34.9854703Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-83-False-True-float16-float16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9854710Z 
2024-02-01T06:36:34.9854821Z Mismatched elements: 1779 / 24931 (7.1%)
2024-02-01T06:36:34.9855140Z Greatest absolute difference: 1.4921875 at index (16, 122) (up to 1e-05 allowed)
2024-02-01T06:36:34.9855414Z Greatest relative difference: 2.46484375 at index (24, 84) (up to 0.001 allowed)
2024-02-01T06:36:34.9856254Z FAILED operators/test_matmul.py::test_op[128-128-32-1-4-2-107-233-83-False-True-bfloat16-bfloat16-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9856261Z 
2024-02-01T06:36:34.9856382Z Mismatched elements: 1568 / 24931 (6.3%)
2024-02-01T06:36:34.9856682Z Greatest absolute difference: 1.5 at index (16, 122) (up to 1e-05 allowed)
2024-02-01T06:36:34.9856927Z Greatest relative difference: 2.46875 at index (24, 84) (up to 0.016 allowed)
2024-02-01T06:36:34.9857737Z FAILED operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-False-False-float16-int8-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9857743Z 
2024-02-01T06:36:34.9857867Z Mismatched elements: 32767 / 32768 (100.0%)
2024-02-01T06:36:34.9858301Z Greatest absolute difference: 365.25 at index (52, 85) (up to 1e-05 allowed)
2024-02-01T06:36:34.9858550Z Greatest relative difference: inf at index (0, 4) (up to 0.001 allowed)
2024-02-01T06:36:34.9859378Z FAILED operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-False-True-float16-int8-True-False-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9859384Z 
2024-02-01T06:36:34.9859515Z Mismatched elements: 32768 / 32768 (100.0%)
2024-02-01T06:36:34.9859820Z Greatest absolute difference: 371.5 at index (52, 85) (up to 1e-05 allowed)
2024-02-01T06:36:34.9860044Z Greatest relative difference: inf at index (0, 4) (up to 0.001 allowed)
2024-02-01T06:36:34.9860863Z FAILED operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-False-False-float16-int8-True-False-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9860870Z 
2024-02-01T06:36:34.9860991Z Mismatched elements: 32767 / 32768 (100.0%)
2024-02-01T06:36:34.9861306Z Greatest absolute difference: 365.25 at index (52, 85) (up to 1e-05 allowed)
2024-02-01T06:36:34.9861529Z Greatest relative difference: inf at index (0, 4) (up to 0.001 allowed)
2024-02-01T06:36:34.9862321Z FAILED operators/test_matmul.py::test_op[128-256-32-1-8-2-None-None-None-False-True-float16-int8-True-True-None-None] - AssertionError: Tensor-likes are not close!
2024-02-01T06:36:34.9862327Z 
2024-02-01T06:36:34.9862453Z Mismatched elements: 32768 / 32768 (100.0%)
2024-02-01T06:36:34.9862754Z Greatest absolute difference: 371.5 at index (52, 85) (up to 1e-05 allowed)
2024-02-01T06:36:34.9862980Z Greatest relative difference: inf at index (0, 4) (up to 0.001 allowed)
```

**Comment by vlad-penkin** [comment] 2024-02-09 06:44
Closing this issue as a duplicate of:
- #381

**Comment by etiotto** [comment] 2024-02-09 14:45
I's like to keep this open until we can verify that IGC has fixed this issue as well as the ones currently a duplicate of this one.

**Comment by quintinwang5** [comment] 2024-03-07 08:23
@chengjunlu Cannot reproduce by just modify `threads_per_warp` and LLVM optimization level. Pls supply more details about this issue.

**Comment by chengjunlu** [comment] 2024-03-07 08:45
No extra step to reproduce this issue. If this issue cannot be reproduced, I think we can close this issue.

**Comment by vlad-penkin** [comment] 2024-03-07 12:06
@etiotto can we close this issue?

**Closed** 2024-03-12 17:30 UTC
Labels: duplicate, dependencies
